# Generated by Django 2.1.7 on 2019-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_batch_number_of_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='cutoff_cpi',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
